2025/05/22 11:13:40 [INFO] Namespace: conf: {'logging_path': 'logs/philbot_runner', 'pipeline_id': None, 'trade_file': 'data/scott-atkinson_20250521_osvC/SPY_2020-01-01_2023-12-31_Day_scott-atkinson_20250521_osvC.csv', 'cash_at_risk': 0.5, 'gamma': 0.99, 'epsilon': 1.0, 'batch_size': 64, 'n_actions': 4, 'eps_min': 0.01, 'input_dims': [6], 'lr': 0.003, 'n_games': 500, 'report_filepath': '/tmp/spy_day_trade.png'}, logging_path: logs/philbot_runner, pipeline_id: scott-atkinson_20250522_QFtK, trade_file: data/scott-atkinson_20250521_osvC/SPY_2020-01-01_2023-12-31_Day_scott-atkinson_20250521_osvC.csv, cash_at_risk: 0.5, gamma: 0.99, epsilon: 1.0, batch_size: 64, n_actions: 4, eps_min: 0.01, input_dims: [6], lr: 0.003, n_games: 500, report_filepath: /tmp/spy_day_trade.png, logfile: logs/philbot_runner/scott-atkinson_20250522_QFtK.log [philbot_runner.py::<module> -- Line 37]
2025/05/22 11:13:40 [INFO] Running main() of /Users/scott.atkinson/src/reinfin/bin/agents/philbot_runner.py [philbot_runner.py::<module> -- Line 39]
2025/05/22 11:13:40 [INFO] Log will appear at logs/philbot_runner/scott-atkinson_20250522_QFtK.log [philbot_runner.py::<module> -- Line 40]
2025/05/22 11:13:40 [ERROR] name 'logging' is not defined [log_wu.py::run_with_logging -- Line 46]
Traceback (most recent call last):
  File "/Users/scott.atkinson/src/reinfin/reinfin/log_wu.py", line 44, in run_with_logging
    fnc(*args)
  File "/Users/scott.atkinson/src/reinfin/bin/agents/philbot_runner.py", line 29, in main
    pr.run_philbot()
  File "/Users/scott.atkinson/src/reinfin/reinfin/agents/philbot_runner.py", line 16, in run_philbot
    logging.info(f"Loading trade_file from {self.conf.trade_file}.")
    ^^^^^^^
NameError: name 'logging' is not defined
2025/05/22 11:13:40 [INFO] Log available at logs/philbot_runner/scott-atkinson_20250522_QFtK.log [log_wu.py::run_with_logging -- Line 49]
